---
#title: "Weather Report "
output:
  officedown::rdocx_document:
    reference_docx: template.docx
always_allow_html: true
params:
  site_selection: !r c("Abbotsinch", "Heathrow")
---

```{r load_data, message=TRUE, warning=FALSE, include=FALSE, paged.print=FALSE}

library("tidyverse")
source("functions.R")


packages <- c("officedown","officer")
loaded_packages <- paste0(search(),sep=" ",collapse = "")
packages <- tibble(package = packages)
packages <- packages %>% mutate(loaded=str_detect(loaded_packages, package, negate = FALSE)) %>% pull(package)

if(length(packages)>0 ){
    for(i in 1:length(packages)){
        result <- require(packages[i],character.only = TRUE)
        if(!result){
            install.packages(packages[i])
            library(packages[i],character.only = TRUE)
        }
    }
}

#don't show code, set image resolution
knitr::opts_chunk$set(echo = FALSE,warning=FALSE,message=FALSE,
 #                     fig.height=8,
                      dpi = 600, dev.args = list(bg = 'transparent'))



#load data and subsetdata Site_Nameand subset
sites <- read_csv("Data/Sites.csv")


sites <- sites %>% filter(Site_Name %in% params$site_selection)

site_names <- paste(params$site_selection,collapse = ", ")

station_data<- data_loader(sites)
processed_data <- aggregate_data(station_data)

layout <- "
##BB
AABB
AACC
##CC
"

```

# Weather Report for `r site_names`

`r run_pagebreak()`

## Seven Day Summary

```{r seven_day_table}

seven_day_datatable(processed_data)
```
`r run_pagebreak()`

## Daily Charts
### Air Temperature


```{r}

plot_data(processed_data,"monthly","mean","air_temperature","Date",title_format="patchwork") 

#  plot_layout(design = layout) +
#  plot_annotation(title="Air Temperature")


```


```{r}
plot_data(processed_data,"daily","max","air_temperature","Date",title_format="patchwork") 

```

```{r}
plot_data(processed_data,"daily","min","air_temperature","Date",title_format="patchwork") 
```

`r run_pagebreak()`
### Relative Humidity

```{r}
plot_data(processed_data,"daily","mean","rltv_hum","Date")
```

```{r}
plot_data(processed_data,"daily","max","rltv_hum","Date")
```

```{r}
plot_data(processed_data,"daily","min","rltv_hum","Date")
```

`r run_pagebreak()`
### Wind Speed

```{r}
plot_data(processed_data,"daily","mean","wind_speed","Date")
```

```{r}
plot_data(processed_data,"daily","max","wind_speed","Date")
```

```{r}
plot_data(processed_data,"daily","min","wind_speed","Date")
```
`r run_pagebreak()`
### Visibility

```{r}
plot_data(processed_data,"daily","mean","visibility","Date")
```

```{r}
plot_data(processed_data,"daily","max","visibility","Date")
```

```{r}
plot_data(processed_data,"daily","min","visibility","Date")
```
